### ISSUE TITLE
在某些情况下会频繁出现这样的问题造成程序的崩溃，而且奇怪的是捕获不到异常

### ISSUE THREAD

**Issue by foxliu** [lulianqi/DubboNet#4]
System.NullReferenceException: Object reference not set to an instance of an object. at NetService.Telnet.ExTelnet.OnRecievedData(IAsyncResult ar) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state) at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by lulianqi** [comment]
> System.NullReferenceException: Object reference not set to an instance of an object. at NetService.Telnet.ExTelnet.OnRecievedData(IAsyncResult ar) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.<>c.b__128_1(Object state) at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

这个数据是全异步收取的，这里的异常在应用层的“Request”是捕获不到的。（所以要改到底层的异步收取不出现没有处理的异常）
不过这个报错信息比较有限，目前只能大致知道是哪个函数异常了，有没有完整的错误堆栈贴以下。

**Comment by foxliu** [comment]
没有堆栈信息，这个问题是偶发性的，在生产服务节点中，只是部分节点出现这个问题，线下调试无法复现出来
